import os

REMEMBER_ME_EXPIRY = 60 * 60 * 24 * 365 * 10
SIGNUP_REDIRECT_URL = ''
LOGIN_REDIRECT_URL = ''
EMAIL_CONFIRMATION_URL = 'account_confirm_email'
CONFIRMATION_EXPIRE_DAYS = 7
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER')